# base ########################################################################
FROM multiarch/debian-debootstrap:armhf-buster-slim as builder

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        wget ca-certificates && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN wget $(wget -qO- http://flightaware.com/adsb/piaware/install | egrep wget -m 1 | awk '{print $3}' | awk -F\< '{print $1}') && \
    dpkg -i piaware*.deb \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -f install -y \
    piaware \
    && DEBIAN_FRONTEND=noninteractive apt-get -f install \
    && DEBIAN_FRONTEND=noninteractive apt-get clean \
    && rm -rf \
      /tmp/* \
      /var/lib/apt/lists/* \
      /var/tmp/*

# final image #################################################################
FROM multiarch/debian-debootstrap:armhf-buster-slim

COPY --from=builder /usr/lib/Tcllauncher1.8 /usr/lib/Tcllauncher1.8

COPY --from=builder /usr/bin/piaware /usr/bin/piaware
COPY --from=builder /usr/lib/piaware /usr/lib/piaware

COPY --from=builder /usr/bin/piaware-config /usr/bin/piaware-config
COPY --from=builder /usr/lib/piaware-config /usr/lib/piaware-config

COPY --from=builder /usr/bin/piaware-status /usr/bin/piaware-status
COPY --from=builder /usr/lib/piaware-status /usr/lib/piaware-status

#COPY --from=builder /usr/bin/pirehose /usr/bin/pirehose
#COPY --from=builder /usr/lib/pirehose /usr/lib/pirehose

COPY --from=builder /usr/lib/piaware_packages /usr/lib/piaware_packages
COPY --from=builder /usr/lib/fa_adept_codec /usr/lib/fa_adept_codec

COPY piaware.conf /etc/piaware.conf
COPY piaware-runner.sh /usr/bin/piaware-runner

EXPOSE 30105/tcp

ENTRYPOINT ["piaware-runner"]

# Metadata
ARG VCS_REF="Unknown"
LABEL maintainer="ginnserv@gmail.com" \
      org.label-schema.name="Docker ADS-B - flightaware" \
      org.label-schema.description="Docker container for ADS-B - This is the flightaware.com component" \
      org.label-schema.url="https://github.com/ShoGinn/docker-ads-b" \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/ShoGinn/docker-ads-b" \
      org.label-schema.schema-version="1.0"
